/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PartService } from "../part.service";
import { PartCreateInput } from "./PartCreateInput";
import { Part } from "./Part";
import { PartFindManyArgs } from "./PartFindManyArgs";
import { PartWhereUniqueInput } from "./PartWhereUniqueInput";
import { PartUpdateInput } from "./PartUpdateInput";

export class PartControllerBase {
  constructor(protected readonly service: PartService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Part })
  async createPart(@common.Body() data: PartCreateInput): Promise<Part> {
    return await this.service.createPart({
      data: data,
      select: {
        createdAt: true,
        id: true,
        partCode: true,
        partId: true,
        partName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Part] })
  @ApiNestedQuery(PartFindManyArgs)
  async parts(@common.Req() request: Request): Promise<Part[]> {
    const args = plainToClass(PartFindManyArgs, request.query);
    return this.service.parts({
      ...args,
      select: {
        createdAt: true,
        id: true,
        partCode: true,
        partId: true,
        partName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Part })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async part(
    @common.Param() params: PartWhereUniqueInput
  ): Promise<Part | null> {
    const result = await this.service.part({
      where: params,
      select: {
        createdAt: true,
        id: true,
        partCode: true,
        partId: true,
        partName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Part })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePart(
    @common.Param() params: PartWhereUniqueInput,
    @common.Body() data: PartUpdateInput
  ): Promise<Part | null> {
    try {
      return await this.service.updatePart({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          partCode: true,
          partId: true,
          partName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Part })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePart(
    @common.Param() params: PartWhereUniqueInput
  ): Promise<Part | null> {
    try {
      return await this.service.deletePart({
        where: params,
        select: {
          createdAt: true,
          id: true,
          partCode: true,
          partId: true,
          partName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
